samubozo/samubozo-front

- package-lock.json
- package.json
- src/components/CommonTabulator.jsx
- src/pages/employee/EmployeeDetail.jsx
- src/pages/employee/EmployeeTable.jsx
- src/pages/employee/EmployeeTable.scss
엑셀 및 pdf 출력 기능 추가(npm install 필수)
> 엑셀 및 pdf 출력 기능 추가(npm install 필수)

- package-lock.json
- package.json
- src/components/Header.jsx
- src/pages/organizationChart/OrgChart.jsx
- src/pages/organizationChart/OrgChart.module.scss
- src/pages/schedule/Schedule.jsx
- src/pages/schedule/Schedule.module.scss
- src/router/AppRouter.jsx
> 조직도 및 일정관리 화면 디자인 완성

- package-lock.json
- package.json
- src/pages/auth/Login.module.scss
- src/pages/main/Dashboard.jsx
- src/pages/main/Dashboard.module.scss
대쉬보드 로그인 화면 수정. 라이브러리 추가되어 npm install 필요
> 대쉬보드 로그인 화면 수정. 라이브러리 추가되어 npm install 필요

- src/pages/auth/Login.jsx
- src/pages/auth/PasswordFind.jsx
- src/pages/auth/PasswordFind.module.scss
- src/pages/auth/PasswordUpdate.jsx
- src/pages/auth/PasswordUpdate.module.scss
- src/pages/auth/Signup.jsx
- src/router/AppRouter.jsx
> 로그인 페이지 보완, 비번 찾기 화면 구현

- src/components/Chatbot.jsx
- src/components/Header.jsx
- src/configs/axios-config.js
- src/configs/host-config.js
- src/context/UserContext.jsx
- src/pages/auth/Login.jsx
> local 스토리지 바라보는거 다 세션으로 변경

- src/components/Chatbot.jsx
- src/configs/axios-config.js
- src/context/UserContext.jsx
- src/pages/auth/Login.jsx
- src/router/AppRouter.jsx
> 로그인 최종 정리 및 챗봇 통신 성공

- index.html
- package-lock.json
- package.json
- src/components/Header.jsx
- src/components/Header.module.scss
- src/configs/axios-config.js
- src/configs/host-config.js
- src/context/UserContext.jsx
- src/pages/auth/Login.jsx
- src/pages/auth/PasswordUpdate.jsx
- src/pages/auth/Signup.jsx
- src/pages/schedule/Schedule.jsx
- src/router/AppRouter.jsx
- src/router/PrivateRouter.jsx
- vite.config.js
> 로그인 토큰 로직 수정. 일정관리 화면 기능 완료

- src/pages/attendance/AttendanceDashboard.module.scss
- src/services/attendanceService.js
- 프론트엔드_데이터_구조_명세서.md
> Attendance2

- package-lock.json
- package.json
- src/main.jsx
- src/pages/schedule/Schedule.jsx
- src/pages/schedule/Schedule.module.scss
리액트 19버전으로 다시 수정. 일정관리 수정(캘린터 카테고리 없으면 일정 추가버튼 비활성화)
> 리액트 19버전으로 다시 수정. 일정관리 수정(캘린터 카테고리 없으면 일정 추가버튼 비활성화)

- src/pages/payroll/PayrollManagement.jsx
- src/pages/payroll/PayrollManagement.module.scss
> 월별 급여 조회 화면 연동을 위한 커밋

- src/pages/attendance/AttendanceDashboard.jsx
- src/pages/attendance/AttendanceDashboard.module.scss
> 근태관리 화면 수정

- src/context/UserContext.jsx
- src/pages/employee/EmployeeDetail.jsx
- src/pages/employee/EmployeeDetail.module.scss
- src/pages/employee/EmployeeTable.jsx
- src/pages/employee/EmployeeTable.module.scss
- src/pages/main/Dashboard.jsx
- src/pages/main/Dashboard.module.scss
인사 관리 퇴사자등록 연동 완료, 사원 일정 행 넘어가면 무한스크롤 구현 완료, 검색 버튼 누를때만 검색 가능하게 수정
> 인사관리 퇴사자등록 연동 완료, 사원 일정 행 넘어가면 무한스크롤 구현 완료, 검색 버튼 누를때만 검색 가능하게 수정

- src/components/Header.jsx
- src/pages/message/Message.module.scss
- src/pages/schedule/Schedule.jsx
> 화면 잡다한 것 수정

- src/pages/auth/PasswordFind.jsx
- src/pages/auth/PasswordFind.module.scss
- src/pages/auth/PasswordUpdate.module.scss
- src/pages/employee/EmployeeDetail.jsx
상세정보 길이제한 추가, 비밀번호 찾기 인증발송 수정(재발송), 비밀번호찾기에 물음표 박스 추가, 비밀번호 찾기 디자인 수정
> 상세정보 길이제한 추가, 비밀번호 찾기 인증발송 수정(재발송), 비밀번호찾기에 물음표 박스 추가, 비밀번호 찾기 디자인 수정

- src/pages/payroll/PayrollManagement.jsx
> Payroll register

- src/components/Header.jsx
hrRole이 Y이면 인사관리와 전자결재 메뉴가 보이게 처리
> hrRole이 Y이면 인사관리와 전자결재 메뉴가 보이게 처리

- src/components/Header.jsx
> 전자결재 hrRole 없앰

- src/pages/employee/EmployeeDetail.jsx
> 주민등록번호 저장할때 하이픈도 같이 저장으로 수정

- src/components/WeatherWidget.jsx
- src/pages/message/Message.jsx
- src/pages/schedule/Schedule.jsx
- src/pages/schedule/Schedule.module.scss
> 호영 화면 전반 수정 커밋

- src/pages/employee/EmployeeDetail.jsx
- src/pages/employee/EmployeeDetail.module.scss
> 인사관리쪽 alert을 커스텀모달로 변경

- src/pages/message/Message.jsx
> 쪽지목록 사용자명 다르게 보이던거 수정

- src/components/Chatbot.jsx
챗봇 입력 오류 수정(4번쨰 ㅡㅡ) 소스 병합 확인 제대로 하셈..
> 챗봇 입력 오류 수정(4번쨰 ㅡㅡ) 소스 병합 확인 제대로 하셈..

- src/pages/payroll/PayrollManagement.jsx
> 출력 로직 일부분 수정

- src/pages/organizationChart/OrgChart.jsx
> 인사팀만 조직도에서 부서 추가 하게 함.

- src/pages/payroll/PayrollManagement.jsx
> 직원 목록 불러오는 로직 변경

- src/pages/payroll/PayrollManagement.jsx
> Payroll modal

- src/configs/host-config.js
> 개발 배포주소 추가

- .github/workflows/deploy.yml
> 자동빌드 시점 메인으로 변경

- .github/workflows/deploy.yml
- src/configs/host-config.js
> 사무보조 버전 1 배포를 위한 푸시

- src/router/AppRouter.jsx
> 로그인 토큰 여부에 따라 루트 경로 분기

- public/error.html
> 루트 경로 로그인 여부에 따라 다르게 처리 

- src/router/PrivateRouter.jsx
해당파일에 /login 으로 보내는 내용있어서 또 수정
> 해당파일에 /login 으로 보내는 내용있어서 또 수정

- public/error.html
> error.html 오타 수정

- src/App.jsx
- src/components/LayoutHeader.jsx
- src/context/UserContext.jsx
- src/context/WeatherContext.jsx
- src/router/PrivateRouter.jsx
> 비로그인자 리다이렉트 문제 해결

- src/configs/host-config.js
> host 주소 변경중

- src/pages/employee/EmployeeDetail.jsx
인사관리에 본인 수정했을 경우 모달창이 제대로 보여지기도 전에 새로고침반영되는거에 딜레이 추가 함
> 인사관리에 본인 수정했을 경우 모달창이 제대로 보여지기도 전에 새로고침반영되는거에 딜레이 추가 함

- src/pages/payroll/PayrollManagement.jsx
> 급여관리 부서명 하드코딩 하는거 동적으로 오게 수정

- src/pages/payroll/PayrollManagement.jsx
> 이름 순회 부분 더 명시적인 이름으로 바꿈

- src/pages/payroll/PayrollManagement.jsx
> 페이롤 건드릴 수록 오류만 나서 원복

- src/components/Chatbot.jsx
- src/pages/auth/PasswordFind.jsx
> 비번 찾기 떄 이메일 아닌거 못보내게 하기  
